error: change `chumsky` traits implementation to use new error
also add inside test reexport for parse::Error so there wouldn't be
conflicts after deleteting Error variants